Open close menu
thecodechaser/portfolio pull request #7
Opened 2021-11-08 19:41 UTC by thecodechaser

This branch includes the following features :
Added javascript, DOM for mobile menu
-When click on the hamburger button, the menu open
-When click on the close button, the menu close 
-When click on any menu item, menu close and take you to clicked section.

2021-11-08 21:39 UTC, rotimiazeez requested changes
# Hi Team 👋, 

### Good job so far👏👏👏
![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

### To Highlight 👏
- No linter errors✔
- Descriptive PR message👏
- Good README 💯

There are some issues that you still need to work on to go to the next project but you are almost there!👍💯.
### Great job so far 👍 just a few changes and you are on to the next level😎💯

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-08 21:39 UTC, rotimiazeez commented on index.html
> +                  alt="hamburger menu"
- [ ] Kindly make sure the hamburger button and menu follow the design from the chosen template in Figma (e.g., font, colours, images, tests, margins).👌
- Your design
![screenshot (15)](https://user-images.githubusercontent.com/44624138/140820863-bc71bc89-a909-46b1-9ad4-3aa553cc668a.png)
- Figma design
![screenshot (16)](https://user-images.githubusercontent.com/44624138/140820959-3a6602ec-def0-4352-92a8-44edf584bbef.png)

2021-11-08 21:39 UTC, rotimiazeez commented on css/stylesheet.css
> +}
- [ ] Kindly make sure your design matches your preferred design😉.
- Figma design
![screenshot (17)](https://user-images.githubusercontent.com/44624138/140821607-73408601-f503-478e-aef9-65b282349039.png)
- Your design
![screenshot (18)](https://user-images.githubusercontent.com/44624138/140821744-3c959227-35f5-4537-9044-be294627f854.png)

2021-11-09 06:04 UTC, Mihndim2020 approved these changes
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @thecodechaser, 

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

![Congratulations-Memes-FEATURED](https://user-images.githubusercontent.com/65852621/133696300-b506e476-dc1a-443e-935a-c6f434e788b6.jpg)

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-09 06:10 UTC, merged